# Generated by Django 2.2.24 on 2023-05-27 18:08

from django.db import migrations, models
from phonenumber_field.phonenumber import PhoneNumber
import phonenumbers


def convert_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.iterator():
        try:
            parsed_number = phonenumbers.parse(flat.owners_phonenumber, 'RU')
            formatted_number = phonenumbers.format_number(parsed_number, phonenumbers.PhoneNumberFormat.E164)
            flat.owner_normalized_phone = PhoneNumber.from_string(formatted_number)
            flat.save()
        except phonenumbers.NumberParseException:
            print(f"Failed to parse phone number for flat {flat.id}")


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_flat_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='owner_normalized_phone',
            field=models.CharField(max_length=15, null=True, blank=True),
        ),
        migrations.RunPython(convert_phone_numbers),
    ]
