# Generated by Django 2.2.24 on 2023-05-27 18:29

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_auto_20230527_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner_normalized_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормальный номер владельца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owners_phonenumber',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер владельца'),
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('phonenumber', models.CharField(max_length=15, verbose_name='Номер телефона')),
                ('normalized_phonenumber', models.CharField(max_length=15, verbose_name='Нормализованный номер телефона')),
                ('flats', models.ManyToManyField(related_name='owners', to='property.Flat', verbose_name='Квартиры')),
            ],
            options={
                'verbose_name': 'Собственник',
                'verbose_name_plural': 'Собственники',
            },
        ),
    ]
