# Generated by Django 2.2.24 on 2023-05-27 18:42

from django.db import migrations
import phonenumbers


def convert_phone_numbers(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')
    for flat in Flat.objects.iterator():
        try:
            owner = Owner.objects.get_or_create(
                full_name=flat.owner,
                phonenumber=flat.owners_phonenumber,
                normalized_phonenumber=phonenumbers.format_number(
                    phonenumbers.parse(flat.owners_phonenumber, 'RU'),
                    phonenumbers.PhoneNumberFormat.E164
                ),
            )
            owner.flats.add(flat)
        except phonenumbers.NumberParseException:
            print(f"Failed to parse phone number for flat {flat.id}")


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20230527_2129'),
    ]

    operations = [
        migrations.RunPython(convert_phone_numbers),
    ]