# Generated by Django 2.2.24 on 2023-05-30 18:18

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_auto_20230527_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterField(
            model_name='flat',
            name='active',
            field=models.BooleanField(db_index=True, verbose_name='Активное объявление'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='address',
            field=models.TextField(help_text='ул. Подольских курсантов д.5 кв.4', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='construction_year',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Год постройки'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания объявления'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание квартиры'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='has_balcony',
            field=models.NullBooleanField(db_index=True, verbose_name='Балкон'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_flats', to=settings.AUTH_USER_MODEL, verbose_name='Лайки'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='living_area',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='owner_normalized_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Нормализованный номер владельца'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='price',
            field=models.IntegerField(db_index=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='rooms_number',
            field=models.IntegerField(db_index=True, verbose_name='Количество комнат'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='town',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='flat',
            name='town_district',
            field=models.CharField(blank=True, help_text='Чертаново Южное', max_length=50, verbose_name='Район города'),
        ),
    ]
