# Generated by Django 2.2.24 on 2023-06-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0012_auto_20230602_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owners',
        ),
        migrations.AddField(
            model_name='flat',
            name='owners',
            field=models.ManyToManyField(related_name='flats', to='property.Owner'),
        ),
    ]
